config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles do
    member do
      get 'approve'
      get 'upgrade/:date' => 'profiles#upgrade', as: 'upgrade'
      get 'reject'
    end
    collection do
      get 'search' => 'profiles#search'
      get 'show_all' => 'profiles#show_all'
      authenticate :user do
        get 'feature' => 'profiles#feature', as: "new_featured_advert"
        get 'dashboard' => 'profiles#dashboard'
      end
    end
  end

  resources :advertisements do
    member do
      get 'pay'
    end
  end

  get '/lektor/:slug', to: 'profiles#show'
  get '/lektor/:slug/upgrade/:date' => 'profiles#upgrade'
  patch '/lektor/:slug', to: 'profiles#update'

  resources :domains
  
  root 'static_pages#home'

  get 'tos' => 'static_pages#tos'
  get 'about' => 'static_pages#about'
  get 'cookie-policy' => 'static_pages#cookie_policy'

  get 'static_pages/help'
  get 'advertise' => 'static_pages#too_many_messages', as: 'advertise'
  resources :messages, only: [:create]
  authenticate :user do
    resources :messages, except: [:create]
    get 'upgrade' => 'payment#index'
    get 'thank-you' => 'payment#thankyou', as: "thankyou"
  end
  
  post 'payments/receive' => 'payment#receive'
  post 'payments/paypal' => 'payment#paypal'

  get '/pl/lektor/:slug', to: 'profiles#show'
  get 'native-speaker-warszawa' => 'profiles#search', defaults: { location: 'Warszawa', language: 'English', lat: '52.2296756', lng: '21.012228700000037' }
  get 'native-speaker-wroclaw' => 'profiles#search', defaults: { location: 'Wrocław', language: 'English', lat: '51.1078852', lng: '17.03853760000004' }
  get 'native-speaker-katowice' => 'profiles#search', defaults: { location: 'Katowice', language: 'English', lat: '50.26489189999999', lng: '19.02378150000004' }
  get 'native-speaker-poznan' => 'profiles#search', defaults: { location: 'Poznań', language: 'English', lat: '52.406374', lng: '16.925168100000064' }
  get 'native-speaker-trojmiasto' => 'profiles#search', defaults: { location: 'Trójmiasto: Gdańsk, Gdynia, Sopot', language: 'English', lat: '54.35202520000001', lng: '18.64663840000003' }
  get 'native-speaker-krakow' => 'profiles#search', defaults: { location: 'Kraków', language: 'English', lat: '50.06465009999999', lng: '19.94497990000002' }
  get 'native-speaker-szczecin' => 'profiles#search', defaults: { location: 'Szczecin', language: 'English', lat: '53.4285438', lng: '14.552811600000041' }
  get 'native-speaker-lodz' => 'profiles#search', defaults: { location: 'Łódź', language: 'English', lat: '51.7592485', lng: '19.45598330000007' }
  get 'native-speaker-lublin' => 'profiles#search', defaults: { location: 'Lublin', language: 'English', lat: '51.2464536', lng: '22.568446300000005' }
  get 'native-speaker-bydgoszcz' => 'profiles#search', defaults: { location: 'Bydgoszcz', language: 'English', lat: '53.12348040000001', lng: '18.008437800000024' }
  get 'native-speaker-torun' => 'profiles#search', defaults: { location: 'Toruń', language: 'English', lat: '53.0137902', lng: '18.59844369999996' }
  get 'native-speaker-czestochowa' => 'profiles#search', defaults: { location: 'Częstochowa', language: 'English', lat: '50.8118195', lng: '19.120309399999996' }

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @languages = Language.all
    @age_groups = AgeGroup.all
    @featured_profiles = @current_domain.profiles.where("featured_until >= ?", Time.now).where(:featured_visible => true)
    @profiles = @current_domain.profiles.where(status: Profile.statuses[:approved]).where("premium_until > ?", Time.now).joins(:user).order('users.last_active_at DESC')
    # this shows non-premium profiles
    # @profiles = @profiles + @current_domain.profiles.where(status: Profile.statuses[:approved]).where("premium_until < ? OR premium_until IS NULL", Time.now).order(created_at: :desc)
  end

  def tos
  end

  def about
  end

  def cookie_policy
  end

  def help
  end

  def too_many_messages
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<br>
<h1>Hi there!</h1>
<p>If you're looking for a native speaker, you've just hit the bull's eye.</p>
<%= image_tag('about.jpg', class: 'img-responsive')%>
<p>Let's see if the following cities are of any interest to you:</p>
<% %w[warszawa wroclaw katowice poznan trojmiasto krakow szczecin lodz lublin bydgoszcz torun czestochowa].each do |city| %>
	<a href="/native-speaker-<%= city %>">Native speakers in <%= city.capitalize %></a><br>
<% end %>

app/views/static_pages/cookie_policy.html.erb
<p><a id="Cookies"></a><strong>Cookies</strong></p>
<p><strong>Cookie Policy</strong></p>
<p><strong>What are cookies?<br></strong>This website uses cookies to collect information.&nbsp; Cookies are small data files which are placed on your computer or other mobile or handheld device (such as smart ‘phones or ‘tablets’) as you browse this website.&nbsp; They are used to ‘remember’ when your computer or device accesses this website.&nbsp; The cookies are essential to the effective operation of our website and to enable to you shop with us online.&nbsp; Cookies are also used to tailor the products and services offered and advertised to our customers, both on this website and elsewhere.&nbsp;</p>
<p><strong>Information collected<br></strong>Some cookies collect information about browsing and purchasing behaviour by people who access this website via the same computer or device.&nbsp; This includes information about pages viewed, products purchased and the customer journey around a website.&nbsp; We do not, however, use cookies to collect or record information on users’ name, address or other contact details.&nbsp; NativeSpeaker.com.pl is able to use cookies to monitor individual customer browsing and purchasing behaviour but third parties are not able to identify customers using cookies.<br><br><strong>Who sets the cookies?<br></strong>The cookies stored on your computer or other device when you access this website are set by NativeSpeaker.com.pl, our suppliers who partner with us to help deliver a high quality website and on-line shopping experience, and other third parties. <br>Some cookies are set by or on behalf of NativeSpeaker.com.pl and are necessary to enable customers to a make purchases on our website.&nbsp; <br>Cookies may also be set by third parties who participate with us in affiliate marketing programmes.&nbsp;&nbsp; The most important such third parties are Criteo and Rich Relevance who broadcast banner advertisements on behalf of NativeSpeaker.com.pl and a number of other reputable companies.&nbsp; None of these third parties collect any personal data from which they would be able to identify individual customers.</p>
<p><br><strong>What are cookies used for?</strong></p>
<p>The main purposes for which cookies are used are:-</p>
<p>1.&nbsp;For technical purposes essential to effective operation of website, particularly in relation to on-line transactions.</p>
<p>2.&nbsp;To drive NativeSpeaker.com.pl marketing, particularly banner advertisements and targeted updates which are explained in more detail elsewhere in the Privacy Policy.</p>
<p>3.&nbsp;To enable NativeSpeaker.com.pl to collect information about the browsing and shopping habits and activities of customers, including to monitor the success of campaigns, competitions etc.&nbsp;</p>
<p>4.&nbsp;To enable NativeSpeaker.com.pl meet its contractual obligations to make payments to third parties when a product is purchased by someone who has visited our website from a site operated by those parties.</p>
<p><strong>How do I disable cookies?<br></strong>If you want to disable cookies you need to change your website browser settings to reject cookies.&nbsp; How to do this will depend on the browser you use and we provide further detail below on how to disable cookies for the most popular browsers:-</p>
<p><strong>For Microsoft Internet Explorer:<br></strong>1.&nbsp;Choose the menu “tools” then “Internet Options”<br>2&nbsp;Click on the “privacy” tab<br>3&nbsp;Select the setting the appropriate setting</p>
<p><strong>For Mozilla firefox:<br></strong>1.&nbsp;Choose the menu “tools” then “Options”<br>2&nbsp;Click on the icon “privacy”<br>3&nbsp;Find the menu “cookie” and select the relevant options</p>
<p><strong>For Opera 6.0 and further:<br></strong>1.&nbsp;Choose the menu Files”&gt; “Preferences”<br>2&nbsp;Privacy</p>
<p><strong>What happens if I disable cookies?<br></strong>This depends on which cookies you disable, but in general the site may not operate properly if cookies are switched off.&nbsp; If you only disable 3rd party cookies you will not be prevented from making purchases on this site.&nbsp; If you disable all cookies you will be unable to complete a purchase on this site.</p>

app/views/static_pages/help.html.haml
%h1 Help
%p (NAME OF THE WEBSITE) is a place where you can put your advertisement of lessons with a native speaker.</p>
%p 
  You can do the following:
  %ul
    %li post an advert
    %li find a native speaker

app/views/static_pages/home.html.erb
<% title project_name, full_title: true %>
<% description 'Aktualna lista native speakerów. Masz w kim wybierać!' %>
<div class="row">
  <div class="col-sm-8">
    <div class="jumbotron yellow-jumbotron city<%= rand(1..5) %>">
      <div class="container">
        <h1>
          <span>
            <strong>find a native speaker</strong>
          </span>
        </h1>
        <form class="form-inline" role="form" action="/profiles/search">
          <div class="form-group">
            <input type="text_field" class="form-control" id="location" placeholder="City" name="location">
          </div>
          <div class="form-group">
            <%= select_tag "language", options_from_collection_for_select(@languages, :name, :name), class: "form-control" %>
          </div> <span id="toggle_search_options" class="btn btn-default" onclick="toggle_search()"> options </span>
          <div id="search_options"><br />
            <div class="form-group">
              <%= select_tag "age_group_id", options_from_collection_for_select(@age_groups, :id, :name), class: "form-control" %>
            </div>
            <div class="form-group">
              <%= select_tag "distance", options_for_select([2,5,10,25,50].map{|x| [x.to_s+' km', x]}, 25), class: "form-control" %>
            </div>
            <div class="form-group">
              <div class="btn-group" data-toggle="buttons">
                <label class="btn btn-default">
                  <%= check_box_tag 'does_online_lessons', 'yes', false, autocomplete: "off", class: 'form-control' %> video lessons
                </label>
                <label class="btn btn-default">    
                   <%= check_box_tag 'works_during_weekend', 'yes', false, autocomplete: "off", class: 'form-control' %> works during weekend
                </label>
                <label class="btn btn-default">
                   <%= check_box_tag 'issues_an_invoice', 'yes', false, autocomplete: "off", class: 'form-control' %> VAT invoice
                </label>
              </div>
            </div>
            <br />
            <br />
          </div>
          <button type="submit" class="btn btn-success">Search</button>
                    <div class="location_details" style="visibility: hidden">
        <%= hidden_field_tag :lat, "", "data-geo"=>"lat" %>
        <%= hidden_field_tag :lng, "", "data-geo"=>"lng" %>
        <%= hidden_field_tag :formatted_address, "", "data-geo"=>"formatted_address" %>
        </div>
        </form>
        <input type="hidden" data-geo="country_code" value="<%= @current_domain.code %>" />
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="jumbotron yellow-jumbotron join-us-background">
      <div class="container">
        <h1>
          <span>
            <strong><%= link_to 'jobs', advertisements_path, class: 'no-decoration' %></strong>
          </span>
        </h1>
        <span class="yellow"><%= link_to 'sign up as a native speaker', user_registration_path, class: 'no-decoration' %></span>
      </div>
    </div>
  </div>
</div>
<div class="container center">
  <div class="row">
   <% @featured_profiles.each do |profile| %>
    <div class="col-md-4 center">
      <%= link_to(image_tag(profile.avatar.url(:medium), class: "bigger-thumb rounded-and-cropped"), profile) %>
      <h2><%= flag_tag profile %> <%= profile.name %></h2>
      <p> <%= profile.languages.collect{|language| "#{language.name}" }.join(", ") %> <br/>
      <% if profile.does_online_lessons %><strong><span class="glyphicon glyphicon-facetime-video online-lessons-icon" aria-hidden="true"></span> Does online lessons!</strong><br/><% end %>
      <%= profile.short_description %></p>
      <p>
        <%= link_to "Show", profile, class: "btn btn-info" %>
                  <span class="btn btn-success"><span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span> <%=   profile.price %> <%= @current_domain.currency %></span>

      </p><br/>
    </div>
   <% end %>


<% if @featured_profiles.count < 3 && @current_profile %>
<div class="col-md-4 center">
      <%= image_tag("questionmark.png", class: "bigger-thumb rounded-and-cropped", alt: "Questionmark") %>
      <h2>You 😱</h2>
      <p> Why not to have your profile featured here? <br>
      <strong> Homepage makes 42 times more views than an average profile</strong><br>
      Offer limited - there are only 3 places here and there won't be any more.</p>
      <p>
        <a class="btn btn-danger" href="<%= upgrade_path %>">Sounds great</a>

      </p><br>
 </div>
 <% end %>



    <span class='clearfix'></span>
  </div>
</div>


<%= render partial: "profiles/profiles_table", locals: {profiles: @profiles} %>
<%= link_to 'show me all native speakers', show_all_profiles_path %> 

app/views/static_pages/too_many_messages.html.haml
%h1 Why bother sending so many messages?
%p We've notied that you send quite a lot messages. You're searching for a native speaker to help you in your company. We get it.
%h2
  But isn't it better to put an advertisement on
  = @current_domain.name
  ?
%p
  We'll help you with that. Just drop me an e-mail.
  = mail_to('adam@nativespeaker.com.pl')
%p Truly yours :) Adam