config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles do
    member do
      get 'approve'
      get 'upgrade/:date' => 'profiles#upgrade', as: 'upgrade'
      get 'reject'
    end
    collection do
      get 'search' => 'profiles#search'
      get 'show_all' => 'profiles#show_all'
      authenticate :user do
        get 'feature' => 'profiles#feature', as: "new_featured_advert"
        get 'dashboard' => 'profiles#dashboard'
      end
    end
  end

  resources :advertisements do
    member do
      get 'pay'
    end
  end

  get '/lektor/:slug', to: 'profiles#show'
  get '/lektor/:slug/upgrade/:date' => 'profiles#upgrade'
  patch '/lektor/:slug', to: 'profiles#update'

  resources :domains
  
  root 'static_pages#home'

  get 'tos' => 'static_pages#tos'
  get 'about' => 'static_pages#about'
  get 'cookie-policy' => 'static_pages#cookie_policy'

  get 'static_pages/help'
  get 'advertise' => 'static_pages#too_many_messages', as: 'advertise'
  resources :messages, only: [:create]
  authenticate :user do
    resources :messages, except: [:create]
    get 'upgrade' => 'payment#index'
    get 'thank-you' => 'payment#thankyou', as: "thankyou"
  end
  
  post 'payments/receive' => 'payment#receive'
  post 'payments/paypal' => 'payment#paypal'

  get '/pl/lektor/:slug', to: 'profiles#show'
  get 'native-speaker-warszawa' => 'profiles#search', defaults: { location: 'Warszawa', language: 'English', lat: '52.2296756', lng: '21.012228700000037' }
  get 'native-speaker-wroclaw' => 'profiles#search', defaults: { location: 'Wrocław', language: 'English', lat: '51.1078852', lng: '17.03853760000004' }
  get 'native-speaker-katowice' => 'profiles#search', defaults: { location: 'Katowice', language: 'English', lat: '50.26489189999999', lng: '19.02378150000004' }
  get 'native-speaker-poznan' => 'profiles#search', defaults: { location: 'Poznań', language: 'English', lat: '52.406374', lng: '16.925168100000064' }
  get 'native-speaker-trojmiasto' => 'profiles#search', defaults: { location: 'Trójmiasto: Gdańsk, Gdynia, Sopot', language: 'English', lat: '54.35202520000001', lng: '18.64663840000003' }
  get 'native-speaker-krakow' => 'profiles#search', defaults: { location: 'Kraków', language: 'English', lat: '50.06465009999999', lng: '19.94497990000002' }
  get 'native-speaker-szczecin' => 'profiles#search', defaults: { location: 'Szczecin', language: 'English', lat: '53.4285438', lng: '14.552811600000041' }
  get 'native-speaker-lodz' => 'profiles#search', defaults: { location: 'Łódź', language: 'English', lat: '51.7592485', lng: '19.45598330000007' }
  get 'native-speaker-lublin' => 'profiles#search', defaults: { location: 'Lublin', language: 'English', lat: '51.2464536', lng: '22.568446300000005' }
  get 'native-speaker-bydgoszcz' => 'profiles#search', defaults: { location: 'Bydgoszcz', language: 'English', lat: '53.12348040000001', lng: '18.008437800000024' }
  get 'native-speaker-torun' => 'profiles#search', defaults: { location: 'Toruń', language: 'English', lat: '53.0137902', lng: '18.59844369999996' }
  get 'native-speaker-czestochowa' => 'profiles#search', defaults: { location: 'Częstochowa', language: 'English', lat: '50.8118195', lng: '19.120309399999996' }

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  enum status: { not_filled_in: 0, pending: 1, rejected: 2, approved: 3 }

  before_create :set_default_values
  before_validation :strip_spaces_in_name, :set_slug

  belongs_to :user
  belongs_to :domain

  validates :short_description, length: { maximum: 180 }
  validates :name, length: {minimum: 5, maximum: 22 }
  validates :price, numericality: { only_integer: true, greater_than: 10, less_than: 300 }
  validates_presence_of :country

  belongs_to :country
  has_and_belongs_to_many :qualifications
  has_and_belongs_to_many :languages
  has_many :messages, foreign_key: "to_id"
  has_and_belongs_to_many :age_groups


  acts_as_mappable :default_units => :kms,
   :default_formula => :flat,
   :distance_field_name => :distance,
   :lat_column_name => :lat,
   :lng_column_name => :lng


  #has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  has_attached_file :avatar, {
    styles: { big: "500x500>", medium: "300x300>", thumb: "100x100>" },
    default_url: ->(attachment) { ActionController::Base.helpers.asset_path('male-placeholder-image.jpg') },
  # Choose the FTP storage backend
  :storage => :ftp,

  # Set where to store the file on the FTP server(s).
  # This supports Paperclip::Interpolations.
  :path => Rails.env+"/:attachment/:id/:style/:filename",

  # The full URL of where the attachment is publicly accessible.
  # This supports Paperclip::Interpolations.
  :url => ENV['ftp_public_path']+Rails.env+"/:attachment/:id/:style/:filename",

  # The list of FTP servers to use
  :ftp_servers => [
    {
      :host     => ENV['ftp_host'],
      :user     => ENV['ftp_user'],
      :password => ENV['ftp_password'],
      :passive  => true  # optional, false by default
    }
  ],

  # Optional socket connect timeout (in seconds).
  # This only limits the connection phase, once connected
  # this option is of no more use.
  # :ftp_connect_timeout => 5, # optional, nil by default (OS default timeout)

  # Optional flag to skip dead servers.
  # If set to true and the connection to a particular server cannot be
  # established, the connection error will be ignored and the files will
  # not be uploaded to that server.
  # If set to false and the connection to a particular server cannot be established,
  # a SystemCallError will be raised (Errno::ETIMEDOUT, Errno::ENETUNREACH, etc.).
  :ftp_ignore_failing_connections => false, # optional, false by default

  # Optional flag to keep empty parent directories when deleting files.
  :ftp_keep_empty_directories => true # optional, false by default
}

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def premium?
    self.premium_until && !self.premium_until.past?
  end

  def featured?
    self.featured_until && self.featured_visible && !self.featured_until.past?
  end

  def self.premium
    where('premium_until > ?', Time.now.utc.to_s(:db))
  end

  def self.plain
    where('premium_until < ?', Time.now.utc.to_s(:db))
  end

  private
  def set_default_values
    self.premium_until ||= Time.now
    self.featured_until ||= Time.now
    self.waiting_messages ||= 0
    self.reminders_sent ||= 0
    self.last_reminder_sent_at ||= Time.now
  end

  def strip_spaces_in_name
    self.name.strip!
    (self.name.include? " ") ? nil : errors.add(:name, 'Your name should contain at least one space')
  end

  def set_slug
    self.slug = self.name.downcase.to_ascii.gsub(/\s+/, '-').gsub(/[^a-z-]/, "") # First it converts spaces to dashes, then deletes all other characters but ascii and dashes
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile_and_authorize, only: [:show, :edit, :update, :destroy, :approve, :reject, :upgrade]

  # GET /profiles
  # GET /profiles.json
  def index
    authorize Profile
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @message = Message.new
  end

  # GET /profiles/new
  def new
    if current_profile.nil?
      @profile = Profile.new
    else
      @profile = current_profile
      render 'edit'
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params.merge(:user_id => current_user.id, :domain_id => current_domain.id ))

    respond_to do |format|
      if @profile.save
        @profile.pending!
        ProfileMailer.waiting_for_approval_mail(@profile).deliver
        format.html { redirect_to upgrade_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: upgrade_path }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    authorize @profile
    respond_to do |format|
      if @profile.update(profile_params)
        unless @profile.premium?
          @profile.pending! 
          ProfileMailer.waiting_for_approval_mail(@profile).deliver
        end
        format.html { redirect_to upgrade_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: upgrade_path }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @distance = params[:distance]
    @distance = 50 unless @distance.present? && @distance.to_i.between?(2,50)
    @location = params[:location]
    search_conditions
    @profiles = Profile.select("profiles.*, users.last_active_at, CASE WHEN profiles.premium_until IS NULL THEN 0 WHEN profiles.premium_until < '#{Time.now.utc.to_s(:db)}' THEN 0 ELSE 1 END AS premium")
                       .where(search_conditions)
                       .where(domain: current_domain).joins(:languages).joins(:age_groups).joins(:user)
                       .where('languages.name = ?', params[:language])
    @profiles = @profiles.within(@distance, origin: [params[:lat], params[:lng]]) if @location.present?
    @profiles = @profiles.order('premium DESC, users.last_active_at DESC')
                         .distinct
    @profiles = @profiles.paginate(page: params[:page], per_page: (params[:per_page] || 50 ) )
  end

  def show_all
    @profiles = Profile.where(domain: current_domain, status: Profile.statuses[:approved]).paginate(page: params[:page], per_page: (params[:per_page] || 50 ) )
  end

  def feature
    authorize @current_profile
    @current_profile.featured_until = 30.minutes.from_now
    @current_profile.featured_visible = false
    render layout: false
  end

  def dashboard
    authorize Profile
    @pending = Profile.pending
    @rejected = Profile.rejected
    @premium = Profile.premium
    @plain = Profile.plain
  end

  def approve
    if @profile.approved!
      ProfileMailer.approved_mail(Profile.last).deliver
      redirect_to @profile, notice: 'Profile was approved!' 
    end
  end
  
  def reject
    if @profile.rejected!
      ProfileMailer.rejected_mail(Profile.last).deliver
      redirect_to @profile, notice: 'Profile was rejected!' 
    end
  end


  def upgrade
    @profile.premium_until = Date.parse(params[:date])
    @profile.save
    redirect_to @profile, notice: "Profile was upgraded until #{Date.parse(params[:date])}" 
  end

  private

  def search_conditions
    age_group_id = AgeGroup.all.map{|ag| ag.id}
    age_group_id = params[:age_group_id] if params[:age_group_id].present?
    does_online_lessons = [true, false, nil]
    does_online_lessons = true if params[:does_online_lessons]=='yes'
    works_during_weekend = [true, false, nil]
    works_during_weekend = true if params[:works_during_weekends]=='yes'
    issues_an_invoice = [true, false, nil]
    issues_an_invoice = true if params[:issues_an_invoice]=='yes'
    {'age_groups.id': age_group_id, does_online_lessons: does_online_lessons, works_during_weekend: works_during_weekend, issues_an_invoice: issues_an_invoice, status: Profile.statuses[:approved] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_profile_and_authorize
    @profile = Profile.find_by(id: params[:id]) || Profile.find_by!(slug: params[:slug], domain: @current_domain)
    authorize @profile
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile)
          .permit(:name, :telephone, :body, :price, :lat, :lng, :formatted_address,
                  :avatar, :short_description, :public_email, :contact_details,
                  :does_online_lessons, :sex, :works_during_weekend,
                  :issues_an_invoice, :country_id,
                  qualification_ids: [], age_group_ids: [], language_ids: [])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def flag_tag(profile)
    image_tag "//flagpedia.net/data/flags/mini/#{profile.country.code.downcase}.png"
  end
end

app/views/profiles/_checkboxes.html.erb
<% if @profile.does_online_lessons %> 
  <strong>
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    Does online lessons
  </strong>
<% else %>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  Doesn't do online lessons
<% end %>
<br/>

<% if @profile.works_during_weekend %> 
  <strong>
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    Works during weekend
  </strong>
<% else %>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  Doesn't work during weekend
<% end %>
<br/>

<% if @profile.issues_an_invoice %> 
  <strong>
    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
    Issues VAT invoices
  </strong>
<% else %>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  Doesn't issue VAT invoices
<% end %>
<br/>

app/views/profiles/_detailed_profiles_table.html.erb
<table class="table table-hover detailed_profiles">
 <!-- <thead>
    <tr>
      <th>Photo</th>
      <th>Flag</th>
      <th>Name</th>
      <th>Qualifications</th>
      <th>Short descritpion & body</th>
      <th>Location</th>
      <th>Average price</th>
      <th></th>
    </tr>
  </thead> !-->

  <tbody>
    <% profiles.each do |profile| %>
      <tr>
        <td><%= link_to(image_tag(profile.avatar.url(:medium), class: "thumb rounded-and-cropped"), profile) %></td>
        <td><%= flag_tag(profile) %></td>
        <td>
        	<%= link_to profile.name, profile %><br/>
        	<%= render partial: "statistics", locals: {profile: profile} %><br/>
          <%= mail_to profile.user.email %>
        </td>
        <td>
          <%= profile.languages.collect{|language| "#{language.name}" }.join(", ") %>
        </td>
        <td></td>
        <td>
        	<strong>Tagline: <%= profile.short_description %></strong> <br/>
        	<div class="profile_description"><a class="show_profile_description" >Description:</a>
            <div class="profile_description_contents" style="display: none;"><%= simple_format(profile.body) %></div>
          </div>
        </td>
        <td class="align-top"><%= profile.formatted_address%></td>
        <td><%= profile.price%>&nbsp;<%= @current_domain.currency %></td>

        <td><%= link_to 'Show', profile, class: "btn btn-success"%>
        <%= (current_user && policy(profile).edit?) ? link_to('Edit', edit_profile_path(profile), class: "btn btn-warning") : "" %>
        <% (current_user && policy(profile).destroy?) ?  link_to('Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" ): ""%>
        	          <% if policy(profile).approve? %>
            <%= link_to '<button type="button" class="btn btn-success">Approve</button>'.html_safe, approve_profile_path(profile) %>
          <% end %>
          <% if policy(profile).reject? %>
            <%= link_to '<button type="button" class="btn btn-danger">Reject</button>'.html_safe, reject_profile_path(profile) %>
          <% end %>
          <% if policy(profile).upgrade? %>
            <%= link_to '<button type="button" class="btn btn-info">Upgrade 1yr</button>'.html_safe, upgrade_profile_path(profile, Date.today + 12.months) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/_form.html.erb
<%= bootstrap_form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-sm-4"><%= f.text_field :name %></div>
    <div class="col-sm-8"><%= f.text_area :short_description, label: "Short description (keep it below 180 characters)", placeholder: "Something short and leading about you that will click with your students-to-be", maxlength: "180"%></div>

    <div class="col-sm-4">
    <%= image_tag @profile.avatar.url(:medium), class: "profile-photo img-responsive rounded-and-cropped" %>

    <%= f.file_field :avatar, label: 'Your photo' %>
    </div>
    <div class="col-sm-8"><%= f.text_area :body, placeholder: "Don't leave the contact details here", rows: 14 %></div>





    <span class="clearfix"></span>
    <br/>

    <div class="col-sm-3"><%= f.collection_check_boxes :qualification_ids, Qualification.all, :id, :name, label: 'Qualifications you have'  %>
    </div>
    <div class="col-sm-3"><%= f.collection_check_boxes(:age_group_ids, AgeGroup.all, :id, :name, label: "Age groups you want to teach")  %></div>
    <div class="col-sm-3">
      <%= f.collection_check_boxes :language_ids, Language.all, :id, :name, label: 'Languages you teach'   %></div>
    <div class="col-sm-3">
        <%= f.collection_select :country_id, Country.all, :id, :name, prompt: true, label: 'Country of origin' %>
        <%= f.select(:sex, options_for_select([['male', 1], ['female', 2]], @profile.sex), prompt: false) %>
        <%= f.label :location %>
        <%= text_field_tag :location, "", class: "form-control" %>
        <div class="location_details">
        <%= f.hidden_field :lat, {"data-geo"=>"lat"} %>
        <%= f.hidden_field :lng, {"data-geo"=>"lng"} %>
        <%= f.hidden_field :formatted_address, {"data-geo"=>"formatted_address"} %>
        </div>
        <%= f.check_box :does_online_lessons, label: "I do online lessons" %>
        <%= f.check_box :works_during_weekend, label: "I work during the weekend" %>
        <%= f.check_box :issues_an_invoice, label: "I issue invoices" %>
        <%= f.number_field :price, label: "Price per clock hour #{@current_domain.currency}"%>
    </div>

    <span class="clearfix"></span>

    <h3>Premium fields</h3>
    <% unless @profile.premium?  %>
      These fields are visible in your profile once you upgrade to a paid membership. Membership options are presented on the next screen.<br>
    <% end %>


    <div class="col-sm-4"><%= f.text_field :telephone %></div>
    <div class="col-sm-4"><%= f.text_field :public_email %></div>
    <div class="col-sm-4"><%= f.text_area :contact_details %></div>




    <%= f.submit %>

<% end %>

app/views/profiles/_profiles_table.html.erb
<table class="table table-hover table-responsive">
 <!-- <thead>
    <tr>
      <th>Photo</th>
      <th>Flag</th>
      <th>Name</th>
      <th>Qualifications</th>
      <th>Short descritpion</th>
      <th>Location</th>
      <th>Average price</th>
      <th></th>
    </tr>
  </thead> !-->

  <tbody>
    <% profiles.each do |profile| %>
      <tr>
        <td><%= profile.premium? ? link_to(image_tag(profile.avatar.url(:medium), class: "thumb rounded-and-cropped"), profile) : ""%></td>
        <td><%= flag_tag(profile) %></td>
        <td><%= link_to profile.name, profile %></td>
        <td>
          <%= profile.languages.collect{|language| "#{language.name}" }.join(", ") %>
        </td>
        <td><%= profile.short_description%></td>
        <td><%= profile.formatted_address%></td>
        <td><%= profile.price%>&nbsp;<%= @current_domain.currency %></td>

        <td><%= link_to 'Show', profile, class: "btn btn-success"%>
        <%= (current_user && policy(profile).edit?) ? link_to('Edit', edit_profile_path(profile), class: "btn btn-warning") : "" %>
        <% (current_user && policy(profile).destroy?) ?  link_to('Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" ): ""%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/_statistics.html.erb
Profile status: <%= profile.status %><br/>
Messages total: <%= profile.messages.count %><br/>
<%= profile.premium? ? 'Premium left for: '+distance_of_time_in_words(Time.now, profile.premium_until) : 'Not premium' %>

app/views/profiles/dashboard.html.erb
<h1>Pending profiles (<%= @pending.count %>)</h1>
<%= render partial: "detailed_profiles_table", locals: {profiles: @pending} %>

<h1>Premium profiles (<%= @premium.count %>)</h1>
<%= render partial: "detailed_profiles_table", locals: {profiles: @premium} %>

<h1>Plain profiles (<%= @plain.count %>)</h1>
<%= render partial: "detailed_profiles_table", locals: {profiles: @plain} %>

<h1>Rejected profiles (<%= @rejected.count %>)</h1>
<%= render partial: "detailed_profiles_table", locals: {profiles: @rejected} %>

app/views/profiles/edit.html.erb
<% title "Edit "+@profile.name %>

<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Telephone</th>
      <th>Price</th>
      <th>User</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name%></td>
        <td><%= profile.telephone%></td>
        <td><%= profile.price%></td>
        <td><%= profile.user%></td>
        <td><%= profile.formatted_address%></td>

        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/show.html.erb
<% title "#{@profile.name} (#{@profile.formatted_address})" %>
<% description @profile.short_description %>
<br/>
  <div class="container">
  	<div class="col-sm-3">
      <%= image_tag @profile.avatar.url(:big), class: "img-responsive img-thumbnail"%>
      <h1 class="text-center">
        <%= flag_tag @profile %> <%= @profile.name %>
      </h1>
      <% if current_user && current_user == @profile.user %>
        <div class="row text-center">
          <%= render partial: "statistics", locals: {profile: @profile} %><br/>
          <% if policy(@profile).approve? %>
            <%= link_to '<button type="button" class="btn btn-success">Approve</button>'.html_safe, approve_profile_path(@profile) %>
          <% end %>
          <% if policy(@profile).reject? %>
            <%= link_to '<button type="button" class="btn btn-danger">Reject</button>'.html_safe, reject_profile_path(@profile) %>
          <% end %>
          <% if policy(@profile).edit? %>
            <%= link_to '<button type="button" class="btn btn-warning">Edit</button>'.html_safe, edit_profile_path(@profile) %>
          <% end %>
          <% if @current_profile.try(:id) == @profile.id %>
            <a href="/upgrade" class="btn btn-primary"><span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span> Upgrade</a>
          <% end %>
          <br/>
          <br/>
        </div>
      <% end %>
      <% if @profile.premium? %>
        <h3>
          <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
          Contact details
        </h3>
        <% if @profile.telephone.present? %>
          <strong>Telephone number:</strong><br/>
          <%= @profile.telephone %><br/>
        <% end %>
        <% if @profile.public_email.present? %>
          <strong>E-mail address:</strong><br/>
          <%= @profile.public_email %><br/>
        <% end %>
        <%= @profile.contact_details %><br/>
      <% end %>
      <div id="map" class="map"></div>
      <%= @profile.formatted_address %><br/>
    </div>
  	<div class="col-sm-8">
      <div class="jumbotron"><h3><%= @profile.short_description %></h3></div>
      <div class="row">
        <div class="col-sm-4">
          <h3>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Qualifications
          </h3>
          <strong>Languages taught:</strong> <%= @profile.languages.collect{|language| "#{language.name}" }.join(", ") %><br/>
          <strong>Qualifications:</strong> <%= @profile.qualifications.collect{|qualification| "#{qualification.name}" }.join(", ") %><br/>
          <strong>Teaching these age groups:</strong> <%= @profile.age_groups.collect{|age_group| "#{age_group.name}" }.join(", ") %><br/>
          <br/><br/>
        </div>
        <div class="col-sm-4">
          <h3>
            <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>
            Starting price
          </h3>
          The starting price <strong>per clock hour</strong> is <%= @profile.price %> <%= @current_domain.currency %>.<br/>
        </div>
        <div class="col-sm-4">
          <h3>
            <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span>
            This and that
          </h3>
          <%= render "checkboxes" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <h3>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            Bits about me
          </h3>
          <%= simple_format(@profile.body) %><br/><br/>
        </div>
      </div>
        <div class="row">
          <div class="col-sm-12 row-no-padding">
          <h3>Leave a message for <%= @profile.name %></h3>
            <%= bootstrap_form_for(@message) do |f| %>
              <%= f.email_field :from, required: true %>
              <%= f.hidden_field :to_id, value: @profile.id %>
              <%= f.text_area :body %>
              <%= check_box_tag 'tos', 'accepted', false, required: true %> I accept the <%= link_to 'Terms of Service', '/tos' %> <br />
              <div class="h-captcha" data-sitekey="fae1b3f9-ddb5-4d8d-a7fd-cbe2d0d8cfee"></div>
              <script src="https://hcaptcha.com/1/api.js" async defer></script>
              <%= f.submit "Submit" %>            <% end %>
              </div><span class="clearfix"></span>
        </div>
    </div>



  
    <script type="text/javascript">

var iconFeature = new ol.Feature({
  geometry: new ol.geom.Point(ol.proj.fromLonLat([<%= @profile.lng %>, <%= @profile.lat %>])),
  name: "<%= @profile.name %>"
});

var iconStyle = new ol.style.Style({
  image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
    anchor: [0.5, 0.5],
    anchorXUnits: 'fraction',
    anchorYUnits: 'fraction',
    opacity: 1,
    src: '<%= asset_path("native_icon.png") %>'
  }))
});

iconFeature.setStyle(iconStyle);

var vectorSource = new ol.source.Vector({
  features: [iconFeature]
});

var vectorLayer = new ol.layer.Vector({
  source: vectorSource
});


var map = new ol.Map({
  layers: [new ol.layer.Tile({
            source: new ol.source.OSM()
          }), vectorLayer],
  target: document.getElementById('map'),
  interactions: ol.interaction.defaults({mouseWheelZoom:false}),
  view: new ol.View({
    center: ol.proj.fromLonLat([<%= @profile.lng %>, <%= @profile.lat %>]),
    zoom: 13
  })
});
/* [<%= @profile.lng %>, <%= @profile.lat %>]  */

    </script>
<br/>

</div>