config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles do
    member do
      get 'approve'
      get 'upgrade/:date' => 'profiles#upgrade', as: 'upgrade'
      get 'reject'
    end
    collection do
      get 'search' => 'profiles#search'
      get 'show_all' => 'profiles#show_all'
      authenticate :user do
        get 'feature' => 'profiles#feature', as: "new_featured_advert"
        get 'dashboard' => 'profiles#dashboard'
      end
    end
  end

  resources :advertisements do
    member do
      get 'pay'
    end
  end

  get '/lektor/:slug', to: 'profiles#show'
  get '/lektor/:slug/upgrade/:date' => 'profiles#upgrade'
  patch '/lektor/:slug', to: 'profiles#update'

  resources :domains
  
  root 'static_pages#home'

  get 'tos' => 'static_pages#tos'
  get 'about' => 'static_pages#about'
  get 'cookie-policy' => 'static_pages#cookie_policy'

  get 'static_pages/help'
  get 'advertise' => 'static_pages#too_many_messages', as: 'advertise'
  resources :messages, only: [:create]
  authenticate :user do
    resources :messages, except: [:create]
    get 'upgrade' => 'payment#index'
    get 'thank-you' => 'payment#thankyou', as: "thankyou"
  end
  
  post 'payments/receive' => 'payment#receive'
  post 'payments/paypal' => 'payment#paypal'

  get '/pl/lektor/:slug', to: 'profiles#show'
  get 'native-speaker-warszawa' => 'profiles#search', defaults: { location: 'Warszawa', language: 'English', lat: '52.2296756', lng: '21.012228700000037' }
  get 'native-speaker-wroclaw' => 'profiles#search', defaults: { location: 'Wrocław', language: 'English', lat: '51.1078852', lng: '17.03853760000004' }
  get 'native-speaker-katowice' => 'profiles#search', defaults: { location: 'Katowice', language: 'English', lat: '50.26489189999999', lng: '19.02378150000004' }
  get 'native-speaker-poznan' => 'profiles#search', defaults: { location: 'Poznań', language: 'English', lat: '52.406374', lng: '16.925168100000064' }
  get 'native-speaker-trojmiasto' => 'profiles#search', defaults: { location: 'Trójmiasto: Gdańsk, Gdynia, Sopot', language: 'English', lat: '54.35202520000001', lng: '18.64663840000003' }
  get 'native-speaker-krakow' => 'profiles#search', defaults: { location: 'Kraków', language: 'English', lat: '50.06465009999999', lng: '19.94497990000002' }
  get 'native-speaker-szczecin' => 'profiles#search', defaults: { location: 'Szczecin', language: 'English', lat: '53.4285438', lng: '14.552811600000041' }
  get 'native-speaker-lodz' => 'profiles#search', defaults: { location: 'Łódź', language: 'English', lat: '51.7592485', lng: '19.45598330000007' }
  get 'native-speaker-lublin' => 'profiles#search', defaults: { location: 'Lublin', language: 'English', lat: '51.2464536', lng: '22.568446300000005' }
  get 'native-speaker-bydgoszcz' => 'profiles#search', defaults: { location: 'Bydgoszcz', language: 'English', lat: '53.12348040000001', lng: '18.008437800000024' }
  get 'native-speaker-torun' => 'profiles#search', defaults: { location: 'Toruń', language: 'English', lat: '53.0137902', lng: '18.59844369999996' }
  get 'native-speaker-czestochowa' => 'profiles#search', defaults: { location: 'Częstochowa', language: 'English', lat: '50.8118195', lng: '19.120309399999996' }

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :profiles
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end

  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:code, :header, :url, :name)
    end
end

app/helpers/domains_helper.rb
module DomainsHelper




end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_field :header %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<%= link_to 'Show', @domain %> |
<%= link_to 'Back', domains_path %>

app/views/domains/index.html.erb
<h1>Listing Domains</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th>Url</th>
      <th>Name</th>
      <th>Header</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.code %></td>
        <td><%= domain.url %></td>
        <td><%= domain.name %></td>
        <td><%= domain.header %></td>

        <td><%= link_to 'Show', domain %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
        <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Domain', new_domain_path %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p>
  <strong>Code:</strong>
  <%= @domain.code %>
</p>

<p>
  <strong>Url:</strong>
  <%= @domain.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @domain.name %>
</p>

<%= link_to 'Edit', edit_domain_path(@domain) %> |
<%= link_to 'Back', domains_path %>