config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles do
    member do
      get 'approve'
      get 'upgrade/:date' => 'profiles#upgrade', as: 'upgrade'
      get 'reject'
    end
    collection do
      get 'search' => 'profiles#search'
      get 'show_all' => 'profiles#show_all'
      authenticate :user do
        get 'feature' => 'profiles#feature', as: "new_featured_advert"
        get 'dashboard' => 'profiles#dashboard'
      end
    end
  end

  resources :advertisements do
    member do
      get 'pay'
    end
  end

  get '/lektor/:slug', to: 'profiles#show'
  get '/lektor/:slug/upgrade/:date' => 'profiles#upgrade'
  patch '/lektor/:slug', to: 'profiles#update'

  resources :domains
  
  root 'static_pages#home'

  get 'tos' => 'static_pages#tos'
  get 'about' => 'static_pages#about'
  get 'cookie-policy' => 'static_pages#cookie_policy'

  get 'static_pages/help'
  get 'advertise' => 'static_pages#too_many_messages', as: 'advertise'
  resources :messages, only: [:create]
  authenticate :user do
    resources :messages, except: [:create]
    get 'upgrade' => 'payment#index'
    get 'thank-you' => 'payment#thankyou', as: "thankyou"
  end
  
  post 'payments/receive' => 'payment#receive'
  post 'payments/paypal' => 'payment#paypal'

  get '/pl/lektor/:slug', to: 'profiles#show'
  get 'native-speaker-warszawa' => 'profiles#search', defaults: { location: 'Warszawa', language: 'English', lat: '52.2296756', lng: '21.012228700000037' }
  get 'native-speaker-wroclaw' => 'profiles#search', defaults: { location: 'Wrocław', language: 'English', lat: '51.1078852', lng: '17.03853760000004' }
  get 'native-speaker-katowice' => 'profiles#search', defaults: { location: 'Katowice', language: 'English', lat: '50.26489189999999', lng: '19.02378150000004' }
  get 'native-speaker-poznan' => 'profiles#search', defaults: { location: 'Poznań', language: 'English', lat: '52.406374', lng: '16.925168100000064' }
  get 'native-speaker-trojmiasto' => 'profiles#search', defaults: { location: 'Trójmiasto: Gdańsk, Gdynia, Sopot', language: 'English', lat: '54.35202520000001', lng: '18.64663840000003' }
  get 'native-speaker-krakow' => 'profiles#search', defaults: { location: 'Kraków', language: 'English', lat: '50.06465009999999', lng: '19.94497990000002' }
  get 'native-speaker-szczecin' => 'profiles#search', defaults: { location: 'Szczecin', language: 'English', lat: '53.4285438', lng: '14.552811600000041' }
  get 'native-speaker-lodz' => 'profiles#search', defaults: { location: 'Łódź', language: 'English', lat: '51.7592485', lng: '19.45598330000007' }
  get 'native-speaker-lublin' => 'profiles#search', defaults: { location: 'Lublin', language: 'English', lat: '51.2464536', lng: '22.568446300000005' }
  get 'native-speaker-bydgoszcz' => 'profiles#search', defaults: { location: 'Bydgoszcz', language: 'English', lat: '53.12348040000001', lng: '18.008437800000024' }
  get 'native-speaker-torun' => 'profiles#search', defaults: { location: 'Toruń', language: 'English', lat: '53.0137902', lng: '18.59844369999996' }
  get 'native-speaker-czestochowa' => 'profiles#search', defaults: { location: 'Częstochowa', language: 'English', lat: '50.8118195', lng: '19.120309399999996' }

end

app/views/layouts/_flash_messages.html.erb
<script>
<% flash.each do |type, message| %>
$.notify({message: '<%= message %>' },{	type: '<%= bootstrap_class_for(type) %>', animate: {
		enter: 'animated fadeInDown',
		exit: 'animated fadeOutUp'
	}, placement: {	from: "top",	align: "center"}});
<% end %>
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
ac&as
</small>

</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-inverse navbar-fixed-top'>
  <div class='container'>
    <div class='navbar-header'>
      <button aria-controls='navbar' aria-expanded='false' class='navbar-toggle collapsed' data-target='#navbar' data-toggle='collapse' type='button'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to(project_name,  "/", class: "navbar-brand") %>
    </div>
    <div class='navbar-collapse collapse' id='navbar'>

      <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li><a href="/about">About</a></li>
              <li><%= link_to 'Jobs', advertisements_path %></li>
              <li><a href="/tos">TOS</a></li>
              <li><a href="/cookie-policy">Cookies</a></li>
              <!--<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>!-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user.nil? %>
                <%= form_for(@user ||= User.new, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f| %>
                  <div class="form-group">
                    <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: 'E-mail'  %>
                  </div>

                  <div class="form-group">
                    <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: 'Password'  %>
                  </div>

                  <div class="form-group">
                    <%= f.submit "Log in", class: "btn btn-success" %>
                  </div>
                  <%= link_to("Sign up", new_user_registration_path, class: "btn btn-danger") %>
                <% end %>

              <% else %>

              <%if @current_profile.nil? %>
              <li><%=link_to "Create profile", new_profile_path %></li>
              <% else %>
              <% badges = ''
                 badges << '<span class="label label-success">premium</span> ' if @current_profile.premium?
                 badges << '<span class="label label-warning">fetured</span>' if @current_profile.featured?
              %>
              <li><%=link_to ('My profile '+badges).html_safe, @current_profile %></a></li>
              <li><%=link_to "My messages", messages_path %></a></li>
              <% end %>
              <li><%=link_to current_user.email, edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete  %></li>
            </ul>
            <% end %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:title) %></title>
    <meta name="description" content="<%= yield(:description) %>"/>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <script src="//maps.googleapis.com/maps/api/js?key=<%=ENV['google_api_key']%>&amp;libraries=places"></script>
    <%= stylesheet_link_tag "ol" %>
    <%= javascript_include_tag "ol" %>
    <link crossorigin="anonymous" href="https://cdnjs.cloudflare.com/ajax/libs/pell/1.0.4/pell.min.css" integrity="sha256-Ld2o3+6zr33AQFbMa5nmnjrvJ+OgdEqYa72WW3LJcto=" rel="stylesheet">/</link>
    <script src="https://wchat.freshchat.com/js/widget.js"></script>
    <script crossorigin="anonymous" integrity="sha256-uGxhgnjkTXSEUIUythHJUF0moiiFbSEWLyS7iA8Yv+E=" src="https://cdnjs.cloudflare.com/ajax/libs/pell/1.0.4/pell.min.js"></script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-7078594687611325",
        enable_page_level_ads: true
      });
    </script>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <script>
    window.fcWidget.init({
      token: "33a0ce77-afc0-4dce-8b46-8dad09d0fd3a",
      host: "https://wchat.freshchat.com"
    });
  </script>
  <body>
    <%= render 'layouts/header' %>
    <%= render partial: "layouts/flash_messages", flash: flash %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-103103139-1', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- Global site tag (gtag.js) - Google Ads: 776116442 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-776116442"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'AW-776116442');
    </script>

  </body>
</html>